version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
    - "8000:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - postgres
    networks:
      - webapp
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - webapp
  postgres:
    image: postgres:12.3-alpine
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - "5440:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - webapp
  cache:
    image: redis:7
    container_name: ${APP_NAME}_redis
    networks:
      - webapp
  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: ${APP_NAME}_cron
    volumes:
      - ./:/var/www/html
    networks:
      - webapp
  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_horizon
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - cache
    networks:
      - webapp
    command: "php artisan horizon"